version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: crawl

    db:
        image: mysql:8.0
        ports:
            - "2071:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: crawl
        volumes:
            - db-data:/var/lib/mysql
            - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
    db-data:
