version: "3.8"

networks:
    db-app:

services:
    app:
        image: sonhoang2071/node-app:latest
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: sonhoang
        networks:
            - db-app

    db:
        image: mysql:8.0
        ports:
            - "2003:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./database.sql:/docker-entrypoint-initdb.d/database.sql
        networks:
            - db-app
